"\x1B[31m[ArgumentError]:\x1B[0m Missing principal input argument!"
"\x1B[31m[ArgumentError]:\x1B[0m Cannot find file "
"\x1B[31m[ArgumentError]:\x1B[0m Some flags requires output path, but no output path is specified!"
"\x1B[31m[ArgumentError]:\x1B[0m Cannot find directory "
"\x1B[31m[ArgumentError]:\x1B[0m Invalid frame rate:"
"\x1B[33m[warning]:\x1B[0m",'FPS is set to '+str(frame_rate)+', which may cause lag in the display!'
"\x1B[31m[ArgumentError]:\x1B[0m Invalid resolution:"
"\x1B[33m[warning]:\x1B[0m",'Resolution is set to more than 3M, which may cause lag in the display!'
"\x1B[31m[ParserError]:\x1B[0m","Unable to parse as dialogue line, due to invalid syntax!"
"\x1B[31m[ParserError]:\x1B[0m","Unable to parse as " + obj_type + " line, due to invalid syntax!"
"\x1B[31m[ParserError]:\x1B[0m","Unable to parse as setting line, due to invalid syntax!"
'\x1B[31m[ParserError]:\x1B[0m Unrecognized switch method: "'+method_name+'" appeared in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Unrecognized switch method: "'+method_name+'" appeared in dialogue line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Failed to load asterisk time in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Too much asterisk time labels are set in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Too much charactor is specified in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Undefined Name '+ name+subtype +' in dialogue line ' + str(i+1)+'. due to:'
'\x1B[31m[ParserError]:\x1B[0m'+' Duplicate subtype '+name+subtype+' is set in charactor table!'
'\x1B[31m[ParserError]:\x1B[0m',E,', which is specified to',name+subtype,'as Animation!'
'\x1B[31m[ParserError]:\x1B[0m','No bubble is specified to major charactor',name+subtype,'of dialogue line '+str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m','Key \''+chatwindow_key+'\' specified to ChatWindow object \''+this_bb+'\' is not exist!'
'\x1B[31m[ParserError]:\x1B[0m','ChatWindow object \''+this_bb+'\' can not be used independently without a specified key!'
'\x1B[31m[ParserError]:\x1B[0m','Invalid symbol (pound mark or vertical bar) appeared in header text of charactor ' + name+subtype+'.'
'\x1B[31m[ParserError]:\x1B[0m',E,', which is specified to',name+subtype,'as Bubble!'
'\x1B[31m[ParserError]:\x1B[0m','Target columns',E,'specified to Bubble object \''+this_bb+'\' is not exist!'
'\x1B[31m[ParserError]:\x1B[0m','Main_Text of "{0}" is None!'
'\x1B[31m[ParserError]:\x1B[0m','Invalid symbol (double quote or backslash) appeared in speech text in dialogue line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Undeclared manual break dialogue line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','More than 4 lines will be displayed in dialogue line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Manual break line length exceed the Bubble line_limit in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Unrecognized text display method: "'+text_method+'" appeared in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Unprocessed asterisk time label appeared in dialogue line ' + str(i+1) + '. Add --SynthesisAnyway may help.'
'\x1B[31m[ParserError]:\x1B[0m The sound effect "'+se_obj+'" specified in dialogue line ' + str(i+1)+' is not exist!'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in dialogue line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m The background "'+bgc+'" specified in background line ' + str(i+1)+' is not defined!'
'\x1B[31m[ParserError]:\x1B[0m Unrecognized switch method: "'+method+'" appeared in background line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in background line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','The switch method of placed animation is dropped, due to short duration!'
'\x1B[31m[ParserError]:\x1B[0m The Animation "'+amo+'" specified in animation line ' + str(i+1)+' is not defined!'
'\x1B[31m[ParserError]:\x1B[0m The Animation "'+amc+'" specified in animation line ' + str(i+1)+' is not defined!'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in animation line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','The switch method of placed bubble is dropped, due to short duration!'
'\x1B[31m[ParserError]:\x1B[0m However impossible!'
'\x1B[31m[ParserError]:\x1B[0m The Bubble expression "'+bbc+'" specified in bubble line ' + str(i+1)+' is invalid syntax!'
'\x1B[31m[ParserError]:\x1B[0m Unrecognized text display method: "'+this_method_label+'" appeared in bubble line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m The Bubble "'+E+'" specified in bubble line ' + str(i+1)+' is not defined!'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in bubble line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Setting',target,'to invalid value',args,',the argument will not changed.'
'\x1B[31m[ParserError]:\x1B[0m The BGM "'+args+'" specified in setting line ' + str(i+1)+' is not exist!'
'\x1B[33m[warning]:\x1B[0m','Using lambda formula range ',dynamic_globals['formula'
'\x1B[31m[ParserError]:\x1B[0m Unsupported formula "'+args+'" is specified in setting line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Unsupported formula "'+args+'" is specified in setting line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Setting',target,'to invalid value',args,',the argument will not changed.'
'\x1B[31m[ParserError]:\x1B[0m Try to modify a undefined column \''+target_column+'\' in charactor table!'
'\x1B[31m[ParserError]:\x1B[0m Try to modify a protected column \''+target_column+'\' in charactor table!'
'\x1B[31m[ParserError]:\x1B[0m Error occurred while modifying charactor table: ' + target + ', due to:'
'\x1B[31m[ParserError]:\x1B[0m Target name \''+ name +'\' in setting line '+str(i+1)+' is not undefined!'
'\x1B[31m[ParserError]:\x1B[0m Error occurred while modifying charactor table: ' + target + ', due to:'
'\x1B[31m[ParserError]:\x1B Target subtype '+ name+'.'+subtype +' in setting line '+str(i+1)+' is not undefined!'
'\x1B[31m[ParserError]:\x1B[0m Unsupported setting "'+target+'" is specified in setting line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Invalid Syntax \''+args+'\' appeared  while repositioning FreePos object \''+target+'\', due to:'
'\x1B[31m[ParserError]:\x1B[0m Unsupported setting "'+target+'" is specified in setting line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in setting line ' + str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','Trying to clear an undefined object'
'\x1B[33m[warning]:\x1B[0m','Trying to clear object',clear_target_name,',which is not a ChatWindow.'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in hitpoint line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m','Invalid syntax, no dice args is specified!'
'\x1B[31m[ParserError]:\x1B[0m Parse exception occurred in dice line ' + str(i+1)+'.'
'\x1B[31m[ParserError]:\x1B[0m Unrecognized line: '+ str(i+1)+'.'
'\x1B[33m[warning]:\x1B[0m','The switch method of placed bubble is dropped, due to short duration!'
'\x1B[31m[ParserError]:\x1B[0m However impossible!'
'\x1B[31m[ParserError]:\x1B[0m Exception occurred while completing the placed medias.'
'\x1B[31m[RenderError]:\x1B[0m Undefined media object : "'+this_frame[layer]+'".'
'\x1B[31m[RenderError]:\x1B[0m Failed to render "'+this_frame[layer]+'" as Background.'
'\x1B[31m[RenderError]:\x1B[0m Failed to render "'+this_frame[layer]+'" as Animation.'
'\x1B[31m[RenderError]:\x1B[0m Failed to render "'+this_frame[layer]+'" as Bubble.'
'\x1B[31m[RenderError]:\x1B[0m Failed to play audio "'+this_frame[key]+'"'
'\x1B[32m'+command+'\x1B[0m'
'\x1B[32m------------------------------------------------------------\x1B[0m'
'\x1B[33m[warning]:\x1B[0m','No valid asterisk label synthesised!'
'\x1B[31m[SynthesisError]:\x1B[0m'
'\x1B[31m[DecodeError]:\x1B[0m'
'\x1B[33m[warning]:\x1B[0m','UTF8 BOM recognized in MediaDef, it will be drop from the begin of file!'
'\x1B[31m[SyntaxError]:\x1B[0m "'+text+'" appeared in media define file line ' + str(i+1)+' is invalid syntax:'
'\x1B[31m[SyntaxError]:\x1B[0m Unable to load charactor table:'
'\x1B[31m[DecodeError]:\x1B[0m'
'\x1B[33m[warning]:\x1B[0m','UTF8 BOM recognized in Logfile, it will be drop from the begin of file!'
'\x1B[32m'+command+'\x1B[0m'
'\x1B[32m------------------------------------------------------------\x1B[0m'
'\x1B[33m[warning]:\x1B[0m Failed to export XML, due to:'
'\x1B[32m'+command+'\x1B[0m'
'\x1B[32m------------------------------------------------------------\x1B[0m'
'\x1B[33m[warning]:\x1B[0m Failed to export Video, due to:'
'\x1B[33m[warning]:\x1B[0m OS exception, --FixScreenZoom is only avaliable on windows system!'
'\x1B[31m[MediaError]:\x1B[0m Exception during converting',media,':'
'\x1B[31m[RenderError]:\x1B[0m','Render exception at frame:'