#!/usr/bin/env python
# coding: utf-8

sourcecode_filelist = [
    "./core/*.py",
    "./doc/*",
    "./gui/*.py",
    "./gui/appframes/*.py",
    "./gui/subwindows/*.py",
    "./media/*.png",
    "./media/icon.ico",
    "./media/occupied_variable_name.list",
    "./media/SE_dice.wav",
    "./media/voice_volume.tsv",
    "./media/*.otf",
    "./meida/tools_scripts/*",
    "./toy/media/*",
    "./toy/CharactorTable.tsv",
    "./toy/LogFile.rgl",
    "./toy/MediaObject.txt",
    "./xml_templates/*",
    "./.gitignore",
    "./export_video.py",
    "./export_xml.py",
    "./LICENSE",
    "./README.md",
    "./replay_generator.py",
    "./requirements.txt",
    "./RplGenCore.py",
    "./speech_synthesizer.py",
]
executable_filelist = [
    "./doc/*",
    "./media/*.png",
    "./media/icon.ico",
    "./media/occupied_variable_name.list",
    "./media/SE_dice.wav",
    "./media/voice_volume.tsv",
    "./media/*.otf",
    "./meida/tools_scripts/*",
    "./toy/media/*",
    "./toy/CharactorTable.tsv",
    "./toy/LogFile.rgl",
    "./toy/MediaObject.txt",
    "./xml_templates/*",
    "./ffmpeg.exe",
    "./ffprobe.exe",
    "./LICENSE",
    "./README.md",
    "./RplGenCore.exe"
    "./回声工坊.exe"
]